// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxvahctwjucwifchpbth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4dmFoY3R3anVjd2lmY2hwYnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTgxMDYsImV4cCI6MjA3MDQ5NDEwNn0.MfuHxiU0_bfu5DAT-EXC_rqQ_7Q0TeObjOTvXbnmTmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});